# Site settings
title: Pushy
email: godexsoft@gmail.com
description: Pushy is a crossplatform, scalable and highly configurable push server with support for APNS and GCM.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
github_username: godexsoft

# Build settings
markdown: kramdown

repository_url: https://github.com/godexsoft/pushy
